# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('referenceID', models.AutoField(primary_key=True, serialize=False)),
                ('referenceLocation', models.FileField(upload_to='reference/')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100)),
                ('sampleLocation', models.FileField(upload_to='sample')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eggs.Reference')),
            ],
        ),
    ]
