# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='referenceLocation',
            new_name='referenceFile',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='sampleLocation',
            new_name='sampleFile',
        ),
    ]
