# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0003_auto_20181017_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='batch',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='eggs.Batch'),
            preserve_default=False,
        ),
    ]
