# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0004_sample_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='timeCreated',
        ),
    ]
