# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0006_batch_timecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eggs.Reference'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eggs.Batch'),
        ),
    ]
