# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0012_auto_20181019_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcfrow',
            name='chrom',
            field=models.CharField(max_length=100, null=True),
        ),    
        migrations.AddField(
            model_name='vcfrow',
            name='pos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vcfrow',
            name='idColInFile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vcfrow',
            name='ref',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vcfrow',
            name='alt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vcfrow',
            name='qual',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vcfrow',
            name='filterColInFile',
            field=models.CharField(max_length=100, null=True),
        ),
         migrations.AddField(
            model_name='vcfrow',
            name='info',
            field=models.CharField(max_length=5000, null=True),
        ),       
        migrations.AddField(
            model_name='vcfrow',
            name='formatColInFile',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
