# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0013_auto_20181019_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcfrow',
            name='formatColInFile',
        ),
        migrations.AddField(
            model_name='vcfrow',
            name='formatNameColInFile',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vcfrow',
            name='formatValueColInFile',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vcfrow',
            name='info',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
