# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0014_auto_20181019_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcfrow',
            name='formatAltAlleleReads',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vcfrow',
            name='formatDP',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vcfrow',
            name='formatRefAlleleReads',
            field=models.IntegerField(null=True),
        ),
    ]
