# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0015_auto_20181023_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vcfrow',
            old_name='formatDP',
            new_name='infoDP',
        ),
    ]
