# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0016_auto_20181023_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vcfrow',
            old_name='formatAltAlleleReads',
            new_name='infoAltAlleleReads',
        ),
        migrations.RenameField(
            model_name='vcfrow',
            old_name='formatRefAlleleReads',
            new_name='infoRefAlleleReads',
        ),
        migrations.RemoveField(
            model_name='vcfrow',
            name='formatNameColInFile',
        ),
        migrations.RemoveField(
            model_name='vcfrow',
            name='formatValueColInFile',
        ),
    ]
