# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0018_auto_20181023_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='significantVariantCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='totalCount',
            field=models.IntegerField(null=True),
        ),
    ]
