# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0023_auto_20181027_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='csvName',
        ),
        migrations.AddField(
            model_name='csv',
            name='csvFile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
