# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0024_auto_20181027_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csvFile',
            field=models.FileField(null=True, upload_to='csv/', verbose_name='Select a CSV File.'),
        ),
    ]
