# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import eggs.storage


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0026_auto_20181119_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csvFile',
            field=models.FileField(null=True, storage=eggs.storage.OverwriteStorage(), upload_to='csv/', verbose_name='Select a CSV File.'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampleFile',
            field=models.FileField(storage=eggs.storage.OverwriteStorage(), upload_to='sample'),
        ),
    ]
