# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import eggs.storage


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0027_auto_20181119_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='csvID',
        ),
        migrations.RemoveField(
            model_name='csv',
            name='csvFile',
        ),
        migrations.AddField(
            model_name='batch',
            name='CsvID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eggs.Csv'),
        ),
        migrations.AddField(
            model_name='csv',
            name='CsvFile',
            field=models.FileField(null=True, storage=eggs.storage.OverwriteStorage(), upload_to='CSV/', verbose_name='Select a CSV File.'),
        ),
    ]
