# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0037_auto_20181208_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='timeCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='csvID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eggs.Csv'),
        ),
    ]
