# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-23 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import eggs.storage


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0045_auto_20181219_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='csvID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eggs.Csv'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='csvFile',
            field=models.FileField(null=True, storage=eggs.storage.OverwriteStorage(), unique=True, upload_to='CSV/', verbose_name='Select a CSV File.'),
        ),
    ]
